name: schemaorg
channels:
  - conda-forge
dependencies:
  - asn1crypto
  - atomicwrites
  - attrs
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - contextlib2
  - coverage
  - cryptography
  - entrypoints
  - flake8
  - icu
  - idna
  - importlib_metadata
  - importlib_resources
  - isodate
  - iso8601
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libiconv
  - libxml2
  - libxslt
  - lxml
  - mccabe
  - more-itertools
  - ncurses
  - nose
  - openssl
  - packaging
  - pip
  - pluggy
  - py
  - pyasn1
  - pycodestyle
  - pycparser
  - pyflakes
  - pyjwt
  - pyopenssl
  - pyparsing
  - pysocks
  - pytest
  - python>=3.6
  - python-dateutil
  - pytz
  - pyxb
  - rdflib
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - urllib3
  - wcwidth
  - wheel
  - xz
  - zipp
  - zlib
  - pip:
    - dataone-cli==3.4.1
    - dataone-common==3.4.1
    - dataone-libclient==3.4.1
    - requests-toolbelt==0.9.1
    - zipstream==1.1.4
prefix: /Users/jevans/anaconda3/envs/schemaorg
